### ISSUE TITLE
Package dependency not installing as expected

### ISSUE THREAD

**Issue by Mark-H** [modxcms/revolution#12541]
Figured I'd give package dependencies a try, but so far it's not working.

The package in question is Mollie for SimpleCart, which has the following in the build script:

```` php
$attributes = array(
    'readme' => file_get_contents($sources['source_core'] . '/docs/readme.txt'),
    'changelog' => file_get_contents($sources['source_core'] . '/docs/changelog.txt'),
    'setup-options' => array(
        'source' => $sources['install_options'] . 'input.options.php',
    ),
    'requires' => array(
        'simplecart' => '>=2.2.15',
    )
);
foreach ($attributes as $k => $v) {
    $package->setAttribute($k, $v);
}
````

Full source available at https://github.com/modmore/SimpleCart_Mollie. 

It uses a slightly different way of packaging, but the requirements are properly added to the package. The package manager also shows the dependencies, as expected:

<img width="906" alt="screen shot 2015-08-10 at 00 24 20" src="https://cloud.githubusercontent.com/assets/312944/9157251/e1f3700c-3ef6-11e5-91c3-c236d1132a46.png">

Interestingly SimpleCart is already downloaded to this particular installation, it's just not installed as I wanted to try the dependencies. 

When I hit install, I get the familiar installer screen for SimpleCart:

<img width="903" alt="screen shot 2015-08-10 at 00 31 22" src="https://cloud.githubusercontent.com/assets/312944/9157254/27999c94-3ef7-11e5-95ec-f8c6964ab17a.png">

Setup options also show up as expected when clicking the button, indicating it managed to find the package and is working with the unzipped manifests. So far so good.

Then this happens:

````
Console running...
Attempting to install package with signature: simplecart_mollie-1.1.2-pl
Package found...now preparing to install.
Grabbing package workspace...
Workspace environment initiated, now installing package...
No filter found.
PHP notice: Undefined index: signature
Could not load package info from name for , not yet implemented.
Package simplecart_mollie-1.1.2-pl requires simplecart @ >=2.2.15
Could not install package with signature: simplecart_mollie-1.1.2-pl
````

It looks like it's trying to install the gateway rather than the core package as instructed. The error `Could not load package info from name for , not yet implemented.` comes from the logging statement I added in #12540 but as it already has the package locally, I'm not sure why it would be trying to find package info from the provider again. 

I've not yet figured out why this is happening and it is absolutely possible it has something to do with our provider, but if someone could confirm they have a working package dependency set up, or any ideas on what to verify/test, I'd be very happy..

**Comment by Mark-H** [comment]
I've just tried it without the simplecart package locally, and that's also not working. Download fails with `Could not download and create transport package with signature:` and the following in the log:

> [2015-08-10 11:01:36] (ERROR in modTransportProvider::latest @ /Applications/MAMP/htdocs/release-2.4/core/model/modx/transport/modtransportprovider.class.php : 185) No filter found.
> [2015-08-10 11:01:36] (ERROR @ /release-2.4/connectors/index.php) Could not load package info from name for , not yet implemented.

**Comment by Mark-H** [comment]
Fixed in #12556

**Comment by BobRay** [comment]
This is still happening to me in 2.4.4. What version has the new code?

**Comment by Mark-H** [comment]
@BobRay The fix was merged into 2.4.0. Might be a different problem you're experiencing?

**Comment by BobRay** [comment]
I wonder if it's because all MyComponent packages do this when there are no setup options:

`$attr['setup-options'] = array();`

**Comment by Mark-H** [comment]
I think you might need to open a new issue and describe exactly what's happening, and how to reproduce the problem ;)

**Comment by BobRay** [comment]
I'm still getting that exact error message in the log. MODX recognizes the dependency, but the download fails. 

```
$attr['requires'] => array(
        'subscribe' => '>=1.2.1',
    )
```
I've tried not setting $attr['setup-options'], and setting it to null, but I'm still getting the same result. I've deleted all core/cache files between each test.

I checked and I *do* have the new code from this commit. I'm running out of stuff to try.

**Comment by BobRay** [comment]
I should have mentioned that the error messages are not exactly the same:

`[2016-04-22 15:52:43] (ERROR in modTransportProvider::latest @ C:\xampp\htdocs\addons\core\model\modx\transport\modtransportprovider.class.php : 185) Package not found.
[2016-04-22 15:52:43] (ERROR @ /addons/connectors/index.php) Could not load package info from name for , not yet implemented.`
