### ISSUE TITLE
Install "undefined" on package management breadcrumb when updating

### ISSUE THREAD

**Issue by pixelchutes** [modxcms/revolution#12567]
### Summary

When _updating_ a package in MODX 2.4.0-pl, the package management overview screen breadcrumb shows:

> Install undefined
### Step to reproduce

Attempt updating  Extra in MODX 2.4.0-pl via the Package Management screen.
### Observed behavior
- "Install undefined" is shown in the breadcrumb:
- Also, "Setup Options" button appears to be cut off.

![package_management](https://cloud.githubusercontent.com/assets/352182/9361886/dda21eb6-465a-11e5-8b49-2ac5d4357956.jpg)
### Expected behavior
- "Install `[Package Name]`" should be displayed vs. `undefined`
- Setup Options button should be fully visible
### Environment

MODX 2.4.0-pl, Chrome 46

NOTE: I verified this on multiple packages, not just MIGX. However, I observed that clicking <kbd>Reinstall</kbd> properly loads the package name.

**Comment by joeke** [comment]
I'll look into this #modxbughunt

**Comment by joeke** [comment]
@pixelchutes Tested this with latest version 2.5.5. This is already fixed. #modxbughunt

**Comment by rtripault** [comment]
So closing.

Feel free to comment/reopen if needed.
Thanks

**Comment by pixelchutes** [comment]
@joeke @rtripault NOTE it happens when **upgrading** a package. I just confirmed the "undefined" is still present in 2.5.5

**Comment by joeke** [comment]
Ah I misunderstood the issue then, sorry for that. Gonna look into it again.

**Comment by joeke** [comment]
@pixelchutes Should be fixed now with PR#13374
