### ISSUE TITLE
TV default media source

### ISSUE THREAD

**Issue by ghost** [modxcms/revolution#12665]
### Summary

TVs have an unreliable default Media Source
### Step to reproduce

Create a new TV and open the Media Sources tab.
### Observed behavior

TV Media Source is the first Media Source you have, in alphabetical order
### Expected behavior

The default Media Source should be the Filesystem source.
### Environment

MODX 2.4.0

possibly related to #12596

**Comment by syts88** [comment]
@sottwell This is indeed fixed in issue #12596. This works in MODX Revo 2.5.5. This issue can be closed. #modxbughunt

**Comment by rtripault** [comment]
Closing as fixed.

Feel free to comment/reopen if needed.
Thanks

**Comment by sottwell** [comment]
I don't see any change in 2.5.5, new TVs still show the first Media Source in alphabetical order.
![screen shot 2017-03-03 at 14 46 46](https://cloud.githubusercontent.com/assets/1073780/23551641/5e657144-0020-11e7-9876-60bff46a0fe6.png)

**Comment by syts88** [comment]
@sottwell indeed. I understood the problem wrong. I will look at it today #modxbughunt.

**Comment by syts88** [comment]
@sottwell I still don't understand the exact issue. 

I have the following media sources; 'Core' and 'Filesystem'. 

I have taken the following actions:

- Create new tv, did not save yet, went to media source tab and for alle my contexten the filesystem is the default media source.

- Saved new tv, went to the media source and the media sources are all set to filesystem.

Did your perhaps meant the dropdown options when you want to change the media source of a context?

**Comment by sottwell** [comment]
No. I mean when creating a new TV, before save, go to the Media Source tab, and it shows the first Media Source in alphabetical order. And if I save the TV without even looking at the Media Source tab, it will be saved with that first alphabetical source.
![screen shot 2017-04-18 at 2 42 39](https://cloud.githubusercontent.com/assets/1073780/25108740/c616dfce-23e0-11e7-9572-6120bdd61aad.png)

**Comment by sottwell** [comment]
This was done with Revo 2.5.6

**Comment by Ibochkarev** [comment]
### Triage (current 3.x)

Mostly addressed on the create path. No need to treat this as “picks alphabetical first” in PHP anymore.

### Comments

Closed briefly as fixed by #12596, then reopened. @sottwell still saw the first A–Z source on new TVs (2.5.6, many sources). @syts88 could not reproduce with only Core + Filesystem.

### Current code

`element/tv/create` seeds the Media Sources tab with `modMediaSource::getDefaultSource()` → system setting `default_media_source` (fallback first source by **id**, not name). That is what gets encoded on save from the full TV form.

So “should be Filesystem” really means “should follow `default_media_source`” (usually Filesystem / id 1).

What can still look wrong is the grid UI: `modx-grid-element-sources` uses a `combocolumn` whose store is `Source/GetList` (sorted by name, `pageSize` 20). If the combo store does not resolve the seeded id cleanly, the tab can show the wrong label even when the underlying id is the default.

I did not re-run a live create with a long source list here.

### Disposition

Confirm on 3.x with many media sources: new TV → Media Sources tab label vs saved `media_sources_elements`. If the saved id matches `default_media_source`, this is display-only (combo/paging). If save still sticks to the A–Z first source, keep as bug. Otherwise close or narrow the title.

Related: #12596 (names), #6660 (default source vs ACL), #13481 (Quick Create skips `sources`).
