### ISSUE TITLE
New PHPMailer and $SMTPAutoTLS

### ISSUE THREAD

**Issue by rutkas** [modxcms/revolution#12762]
New PHP mailer 5.2.13 now has a feature $SMTPAutoTLS = true that:
/**
     \* Whether to enable TLS encryption automatically if a server supports it,
     \* even if `SMTPSecure` is not set to 'tls'.
     \* Be aware that in PHP >= 5.6 this requires that the server's certificates are valid.
     \* @type boolean
*/
So currently even if we leave mail_smtp_prefix blank - the mailer forces TLS, and that is not always good. So I think it is reasonable to create a new system option like "mail_smpt_force_tls" that will change $SMTPAutoTLS to true or false before PHPMailer calls.

**Comment by JoshuaLuckers** [comment]
Is this issue still relevant?

**Comment by Ibochkarev** [comment]
@JoshuaLuckers After version 5.2.13 there are 27 releases. And at the moment a lot has changed.
I would close this issue.

The current version is currently 6.0.7

**Comment by zaigham** [comment]
I think this no longer relevant due to this: https://github.com/modxcms/revolution/pull/13886

**Comment by JoshuaLuckers** [comment]
Is `SMTPAutoTLS` still set to `true` by default?

**Comment by rutkas** [comment]
I think SMTPAutoTLS is still true by default. and the issue still exists.

Dear Ibochkarev, take a look at this link, the problem is still well known (2018 post):
https://modx.pro/help/16267

People making some hacks to avoid this bug in 2018, but I reported this issue in 2015.

And it is is bad practice to close active issues, only because of a reason like "After version 5.2.13 there are 27 releases. And at the moment a lot has changed". The issue is not in PHP mailer. they just changed some behavior, do you think they changed it back after many releases ? I can not believe it
Personally, I fixed my issue by configuring TLS on my server and forgot about this problem. I spent my time to discover the problem and report this issue here not to get such answer after 4 years, but to improve the project :) I even proposed how to fix it easily.

**Comment by Ibochkarev** [comment]
@rutkas Excuse me. So this problem should be solved.

Please re-open this problem again.

Thank!

**Comment by OptimusCrime** [comment]
This problem is indeed not solved. We had to roll our own wrapper around PHPMailer to get access to this setting.

**Comment by Jako** [comment]
@rutkas, @OptimusCrime Do you have a patch available for solving this issue?

**Comment by JoshuaLuckers** [comment]
I think we should add a new system setting  with as key `smtp_auto_tls` under "E-mail". 
By default it should be set to `true`.

**Comment by Ibochkarev** [comment]
@Jako I will prepare PR

**Comment by rutkas** [comment]
Yes, smtp_auto_tls option, that just sets $SMTPAutoTLS to true or false before calling PHP Mailer would be fine.

**Comment by OptimusCrime** [comment]
@JoshuaLuckers Would it not make more sense to expose the setter/getter via modPHPMailer? Then you can set it conditionally, instead of automatically using the system setting.

**Comment by JoshuaLuckers** [comment]
> @JoshuaLuckers Would it not make more sense to expose the setter/getter via modPHPMailer? Then you can set it conditionally, instead of automatically using the system setting.

Yes and users should be able to set the behaviour via a system setting as well.

**Comment by muzzwood** [comment]
I just got the following pop up:
Deprecated: __autoload() is deprecated, use spl_autoload_register() instead in /home/vagrant/code/site/public_html/core/model/modx/mail/phpmailer/PHPMailerAutoload.php on line 45

So I assume it's related to this issue.

**Comment by OptimusCrime** [comment]
@digitalpenguin It is not related to this issue.

**Comment by funkyduke** [comment]
I'm in the same situation I think. I want to use a mailserver from our hostingprovider but they don't use SSL or TLS on that server, so I leave the system option blank in Modx but that doesn't work. Will this be on the next release of Modx?

**Comment by JoshuaLuckers** [comment]
You can modify the file directly to set the setting, there is no system setting yet (I'm not sure if we are going to include a setting for it in the next release). 
The best solution would be using SSL and urge providers to support it when they don't do so.

**Comment by Ibochkarev** [comment]
@Jako https://github.com/modxcms/revolution/pull/15491 Is it still relevant after the update?

**Comment by Jako** [comment]
It seems to work the same as before on my mailhost:

- mail_smtp_prefix = '', Port 25 -> Mail is sent (but Quickmail says `CLIENT -> SERVER: STARTTLS`)
- mail_smtp_prefix = '', Port 587 -> Mail is sent (but Quickmail says `CLIENT -> SERVER: STARTTLS`)
- mail_smtp_prefix = 'tls', Port 587 -> Mail is sent
- mail_smtp_prefix = 'ssl', Port 465 -> Mail is sent

So it looks like the bug is still there. Maybe someone else can test this too.

We need a system setting for SMTPAutoTLS.

**Comment by Ibochkarev** [comment]
Added in https://github.com/modxcms/revolution/pull/15536
