### ISSUE TITLE
MODX 3: login page checkbox

### ISSUE THREAD

**Issue by meshkov** [modxcms/revolution#13948]
### Summary
checkbox on the login page is off-center
![2018-07-03_10-24-55](https://user-images.githubusercontent.com/1703670/42204978-d836dca0-7eab-11e8-9735-c33787618b9d.png)

### Environment
MODX 3.0
Windows 10
Google Chrome 67.0.3396.99

**Comment by jonleverrier** [comment]
I wonder if this is a Windows issue. As I can't reproduce on;
MacOSX 10.13.4
MODX3 Alpha v 3.0.0-dev

Firefox 61.0
![screen shot 2018-07-03 at 16 56 39](https://user-images.githubusercontent.com/2373940/42227585-1e44b2ae-7ee2-11e8-82ce-9561397c8588.png)

Chrome Version 67.0.3396.99
![screen shot 2018-07-03 at 16 57 24](https://user-images.githubusercontent.com/2373940/42227638-371f384e-7ee2-11e8-8261-ba09d17038fa.png)

Safari 11.1
![screen shot 2018-07-03 at 16 58 12](https://user-images.githubusercontent.com/2373940/42227676-4ddec5a4-7ee2-11e8-99cc-31b29055aa8a.png)

**Comment by meshkov** [comment]
Test on MacOSX 10.3.5 in Chrome Version 67.0.3396.99 and all is well.

But problem exist on Windows 10 in Google Chrome 67.0.3396.99.

And on iOS 11.4 Safari:
![photo_2018-07-03_22-39-23](https://user-images.githubusercontent.com/1703670/42241139-3389672e-7f12-11e8-8f18-2dc2d2f78e5a.jpg)
![photo_2018-07-03_22-39-50](https://user-images.githubusercontent.com/1703670/42241222-7b2bd1ca-7f12-11e8-969f-d1a6bc9d79ef.jpg)

**Comment by Ibochkarev** [comment]
This problem has been fixed earlier.

**Tested in browsers:**
Google Chrome 71.0.3578.98
Safari 12.0.2 (13606.3.4.1.4)
Firefox Developer Edition 65.0b9 (64-bit)

MacOS High Sierra 10.13.6 (17G4015)
MODX 3.0.0-pl

![Tested](https://github.com/Ibochkarev/other-repo/blob/54a25c71f12f6a92d132f71a6340d34188fda2a3/%2313948.png?raw=true)

I vote for closing this problem.

**Comment by Ruslan-Aleev** [comment]
In Windows OS the problem is not solved.
**Its better to make the icon checkbox, not standard.**

**Comment by JoshuaLuckers** [comment]
The alignment of the checkbox and text needs some tweaking. I'm leaving this issue open.

**Comment by JoshuaLuckers** [comment]
This issue seems to be solved by PR #14310, therefore I'm closing this issue.
