### ISSUE TITLE
Some ids in the database have inconsistent length values - int(x).

### ISSUE THREAD

**Issue by patrickatwsrn** [modxcms/revolution#15741]
### Summary

I just noticed some inconsistencies in the database.

Most primary key ids use int(10), but some have int(9) or int(11).  Some string-based keys also don't have consistant length values (100 or 191) even though they interact with each other.

### Observed behavior
* modx_active_users -  internalKey - int(9)

* modx_media_sources_contexts  - int(11) BUT  modx_media_sources  - id - int(10)
* modx_media_sources_elements  - int(11) BUT modx_media_sources  - id - int(10)

 * modx_context_resource - context_key varchar(191) BUT modx_context  - key - varchar(100)
 * modx_context_setting  - context_key - varchar(191) BUT modx_context  - key - varchar(100)

* modx_site_tmplvar_templates - templateid - int(11) BUT modx_site_templates  - id - int(10)
* modx_user_settings  - user - id(11) BUT modx_users  - id - int(10)

Some extras also have inconsistant values (if somebody is interested in a proper bug report, let me know):

* modx_fc_profiles_usergroups - usergroup - int(11)
* modx_fc_sets  - id - int(10)

* modx_formalicious_fields  - id - int(10) - the other 5 tables have int(11)
* modx_seosuite_social - resource_id(11) - doesn't make sense if the id for modx_site_content is int(10)
* all versionx tables are using int(11)

### Expected behavior
Numeric ids should be either int(10) OR int(11) across the board.
String ids shold be consistant. varchar(191)

### Implications
As far as I understand it doesn't seem to matter at the end of the day. 

If I'm wrong here and in fact onto something that might become a problem, it would be great if somebody could share his knowledge about this topic.

Cheers,

Patrick

Edit: 
If I'm reading the specs right, the length of an int-base id could be 1 and still fit any number up to 4294967295 (unsigned). The length only says how integers are displayed in external applications:

> MySQL lets you specify a “width” for integer types, such as INT(11). This is meaningless for most applications: it does not restrict the legal range of values, but simply specifies the number of characters MySQL’s interactive tools (such as the command-line client) will reserve for display purposes. For storage and computational purposes, INT(1) is identical to INT(20). 
> Source: https://www.oreilly.com/library/view/high-performance-mysql/9781449332471/ch04.html

**Comment by opengeek** [comment]
All integer fields representing primary and foreign keys should be unsigned INT fields, which would effectively be int(11), regardless of the specified "width." The consistency definitely should be addressed with regards to the unsigned attribute and width. But it is effectively not a problem in real-world usage. Keep this open, and let's address it.

**Comment by Ibochkarev** [comment]
Still the same on 3.x. @opengeek's note holds: this does not change what a normal site can store, and the schema should still be lined up.

INT(9), INT(10) and INT(11) are one 4-byte integer. The number in parentheses is a display width. MySQL 8.0.17 deprecates that width for integer types. The edit on the report already quotes the same point from High Performance MySQL. A signed INT stops at 2147483647. An unsigned INT goes to 4294967295. That signedness is the part worth fixing on columns that point at an id.

Core ids that this schema defines are `int` precision 10 unsigned, including `modAccessibleSimpleObject.id` in `core/model/schema/modx.mysql.schema.xml`. These columns still disagree with that:

- `modMediaSourceContext.source` is precision 11 with no unsigned, in `core/model/schema/modx.sources.mysql.schema.xml`. `modMediaSourceElement.source` and `object` are precision 11 unsigned.
- `modFormCustomizationProfileUserGroup.usergroup` and `profile` are precision 11 with no unsigned. That table is core (`fc_profiles_usergroups`).
- `modActiveUser.internalKey` is precision 9 unsigned. `modContextResource.resource`, `modTemplateVarTemplate.templateid`, and `modUserSetting.user` are precision 11 unsigned.

Set those to `dbtype="int" precision="10" attributes="unsigned"`, and apply the same `ALTER` in an upgrade for existing databases. Rank, login count, and the other counters can stay. They are not ids.

`modContext.key` is varchar(100). `modContextSetting.context_key` and `modContextResource.context_key` are varchar(191). Media source and access rows already store `context_key` as varchar(100). Bring those two columns down to 100 so they match the context key. A context key cannot be longer than `modContext.key`. varchar(191) on other indexed strings is the utf8mb4 index ceiling, separate from this key.

Formalicious, SEO Suite, and VersionX are extras. Their widths belong in those projects.
